# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Launcher
Launcher_APPLICATION_ICON = Launcher.tiff
Launcher_RESOURCE_FILES = Launcher.tiff
Launcher_ḦEADERS = launcher.h
Launcher_OBJC_FILES = main.m  launcher.m


include $(GNUSTEP_MAKEFILES)/application.make